namespace GardeningHelperDatabase.Seed
{
    public class Constants
    {
        public const string Admin = "Admin";
        public const string User = "User";
        public const string PlantsJson = @"
        [
            {
            ""Name"": ""Rose"",
            ""SunlightRequirements"": ""FullSun"",
            ""SoilType"": ""Loamy"",
            ""GrowthPeriod"": ""5-9"",
            ""HarvestTime"": ""Spring"",
            ""MinTemperature"": 5.0,
            ""MaxTemperature"": 30.0,
            ""MinHumidity"": 40.0,
            ""MaxHumidity"": 70.0,
            ""MinRainfall"": 20.0,
            ""MaxRainfall"": 60.0,
            ""MinSoilMoisture"": 30.0,
            ""MaxSoilMoisture"": 60.0,
            ""WateringThresholdDays"": 7,
            ""WateringThresholdRainfall"": 10.0
            },
            {
            ""Name"": ""Tulip"",
            ""SunlightRequirements"": ""FullSun"",
            ""SoilType"": ""Sandy"",
            ""GrowthPeriod"": ""3-6"",
            ""HarvestTime"": ""Spring"",
            ""MinTemperature"": 0.0,
            ""MaxTemperature"": 25.0,
            ""MinHumidity"": 30.0,
            ""MaxHumidity"": 60.0,
            ""MinRainfall"": 15.0,
            ""MaxRainfall"": 50.0,
            ""MinSoilMoisture"": 20.0,
            ""MaxSoilMoisture"": 50.0,
            ""WateringThresholdDays"": 5,
            ""WateringThresholdRainfall"": 5.0
            },
            {
            ""Name"": ""Lavender"",
            ""SunlightRequirements"": ""FullSun"",
            ""SoilType"": ""Sandy"",
            ""GrowthPeriod"": ""5-9"",
            ""HarvestTime"": ""Summer"",
            ""MinTemperature"": 10.0,
            ""MaxTemperature"": 35.0,
            ""MinHumidity"": 20.0,
            ""MaxHumidity"": 50.0,
            ""MinRainfall"": 10.0,
            ""MaxRainfall"": 40.0,
            ""MinSoilMoisture"": 15.0,
            ""MaxSoilMoisture"": 40.0,
            ""WateringThresholdDays"": 10,
            ""WateringThresholdRainfall"": 5.0
            },
            {
            ""Name"": ""Tomato"",
            ""SunlightRequirements"": ""FullSun"",
            ""SoilType"": ""Loamy"",
            ""GrowthPeriod"": ""5-9"",
            ""HarvestTime"": ""Summer"",
            ""MinTemperature"": 15.0,
            ""MaxTemperature"": 30.0,
            ""MinHumidity"": 40.0,
            ""MaxHumidity"": 70.0,
            ""MinRainfall"": 30.0,
            ""MaxRainfall"": 70.0,
            ""MinSoilMoisture"": 40.0,
            ""MaxSoilMoisture"": 70.0,
            ""WateringThresholdDays"": 3,
            ""WateringThresholdRainfall"": 10.0
            },
            {
            ""Name"": ""Pepper"",
            ""SunlightRequirements"": ""FullSun"",
            ""SoilType"": ""Loamy"",
            ""GrowthPeriod"": ""5-9"",
            ""HarvestTime"": ""Summer"",
            ""MinTemperature"": 18.0,
            ""MaxTemperature"": 32.0,
            ""MinHumidity"": 40.0,
            ""MaxHumidity"": 70.0,
            ""MinRainfall"": 25.0,
            ""MaxRainfall"": 60.0,
            ""MinSoilMoisture"": 35.0,
            ""MaxSoilMoisture"": 65.0,
            ""WateringThresholdDays"": 4,
            ""WateringThresholdRainfall"": 10.0
            },
            {
            ""Name"": ""Cucumber"",
            ""SunlightRequirements"": ""FullSun"",
            ""SoilType"": ""Loamy"",
            ""GrowthPeriod"": ""5-9"",
            ""HarvestTime"": ""Summer"",
            ""MinTemperature"": 16.0,
            ""MaxTemperature"": 30.0,
            ""MinHumidity"": 50.0,
            ""MaxHumidity"": 80.0,
            ""MinRainfall"": 30.0,
            ""MaxRainfall"": 70.0,
            ""MinSoilMoisture"": 40.0,
            ""MaxSoilMoisture"": 70.0,
            ""WateringThresholdDays"": 2,
            ""WateringThresholdRainfall"": 10.0
            },
            {
            ""Name"": ""Carrot"",
            ""SunlightRequirements"": ""FullSun"",
            ""SoilType"": ""Sandy"",
            ""GrowthPeriod"": ""4-9"",
            ""HarvestTime"": ""Fall"",
            ""MinTemperature"": 10.0,
            ""MaxTemperature"": 25.0,
            ""MinHumidity"": 40.0,
            ""MaxHumidity"": 70.0,
            ""MinRainfall"": 20.0,
            ""MaxRainfall"": 50.0,
            ""MinSoilMoisture"": 30.0,
            ""MaxSoilMoisture"": 60.0,
            ""WateringThresholdDays"": 5,
            ""WateringThresholdRainfall"": 10.0
            },
            {
            ""Name"": ""Potato"",
            ""SunlightRequirements"": ""FullSun"",
            ""SoilType"": ""Loamy"",
            ""GrowthPeriod"": ""4-9"",
            ""HarvestTime"": ""Fall"",
            ""MinTemperature"": 10.0,
            ""MaxTemperature"": 25.0,
            ""MinHumidity"": 40.0,
            ""MaxHumidity"": 70.0,
            ""MinRainfall"": 30.0,
            ""MaxRainfall"": 60.0,
            ""MinSoilMoisture"": 35.0,
            ""MaxSoilMoisture"": 65.0,
            ""WateringThresholdDays"": 5,
            ""WateringThresholdRainfall"": 10.0
            }
        ]";
    }
}
